### PR TITLE
perf: convert scan to direct sum for gas consumption

### PR DESCRIPTION
**Pull request by beckermr**
This PR converts a scan operation in the gas consumption convolution to a direct sum. Maybe it will help with performance, maybe not!

### CODE REVIEW

**Comment by aphearin** [comment]
Not sure why `tests_cron.yml` isn't showing up as a check, but I just ran the full test suite locally and it passes.

**Comment by beckermr** [comment]
Oooooh that makes more sense. I ran the test suite locally but was curious why it wasn't in CI. Idk what is going on with that gha workflow. It looks fine to me.

**Comment by beckermr** [comment]
GitHub says the test suite was ma shall disabled. Maybe you turned it off for a bit?

**Comment by aphearin** [comment]
Not sure how that happened - not intentionally

**Comment by aphearin** [comment]
Ok they were apparently turned off due to 60-day inactivity. I just turned them back on.

**Comment by aphearin** [comment]
The small change in 56e16bb18faa506c6bf222be994cfef24fea38e1 just simplified doing a timing test of the new kernels computing SFHs for large galaxy populations. Depending on the size of Ngal and t_table, the speedup factor (on a CPU) brought in with this new kernel ranges from 1.5x to 3x. This faster kernel is now the default.

**Pull request merged**
